apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim-prometheus
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      volume-type: nfs
      pv-name: pvvol-prometheus
