apiVersion: v1
kind: PersistentVolume
metadata:
 name: pvvol-prometheus
 labels: 
    volume-type: nfs
    pv-name: pvvol-prometheus
spec:
 capacity:
  storage: 50Gi
 accessModes:
   - ReadWriteMany
 persistentVolumeReclaimPolicy: Retain
 nfs:
   path: /exports/prometheus
   server: nfs.olsclab.net
   readOnly: false
