apiVersion: v1
kind: PersistentVolume
metadata:
 name: pvvol-grafana
 labels: 
    volume-type: nfs
    pv-name: pvvol-grafana
spec:
 capacity:
  storage: 50Gi
 accessModes:
   - ReadWriteMany
 persistentVolumeReclaimPolicy: Retain
 nfs:
   path: /exports/grafana
   server: nfs.olsclab.net
   readOnly: false
